# Generated by Django 2.0.12 on 2020-02-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_auto_20180424_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
